spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  application:
    name: test
server:
  servlet:
    context-path: /bloom
  port: 12342

credit:
  local-path: C:\temp\
#密文过期时间，单位 小时
redis:
  expire-time: 12

mongo:
  storage:
    prefix: daily_storage_